os: osx
osx_image: xcode11.2
language: swift
script: xcodebuild clean build test -project "QuotesMaker.xcodeproj" -scheme "QuotesMaker" -sdk iphonesimulator -destination  "platform=iOS Simulator,name=iPhone 8" ONLY_ACTIVE_ARCH=NO CODE_SIGNING_REQUIRED=NO