# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#


default_platform(:ios)

platform :ios do
  lane :register_app do
    produce (
      username: "cwcodesworth@gmail.com",
      app_identifier: "com.codesworth.QuoteStudio",
      app_name: "Quote Studio",
      team_name: "Shadrach Mensah",
      itc_team_name: "Shadrach Mensah"
    )
  end
end
